namespace DataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddAutoGeneratedIds : DbMigration
    {
        public override void Up()
        {
            //DropForeignKey("dbo.ExerciseQuestions", "CorrectOption_Id", "dbo.MultipleChoiceOptions");
            //DropPrimaryKey("dbo.MultipleChoiceOptions");
            //AlterColumn("dbo.MultipleChoiceOptions", "Id", c => c.Guid(nullable: false, identity: true));
            //AddPrimaryKey("dbo.MultipleChoiceOptions", "Id");
            //AddForeignKey("dbo.ExerciseQuestions", "CorrectOption_Id", "dbo.MultipleChoiceOptions", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.ExerciseQuestions", "CorrectOption_Id", "dbo.MultipleChoiceOptions");
            DropPrimaryKey("dbo.MultipleChoiceOptions");
            AlterColumn("dbo.MultipleChoiceOptions", "Id", c => c.Guid(nullable: false));
            AddPrimaryKey("dbo.MultipleChoiceOptions", "Id");
            AddForeignKey("dbo.ExerciseQuestions", "CorrectOption_Id", "dbo.MultipleChoiceOptions", "Id");
        }
    }
}
